### PR TITLE
Update EC rates

### PR DESCRIPTION
**Pull request by giraudsimon**
- updated EC rates input tables, corresponds to rates employed in https://doi.org/10.48550/arXiv.2412.00650 for GT(SM+EDF) results, with tables from here: https://groups.frib.msu.edu/charge_exchange/weakrates.html. EC rates can be set to GT+FF(EDF) of the paper by changing, in parameters file, iravlic to priority 1, iapprox to 2 and others to 0.

- Besides changes related to input tables, please note the new if condition in weakrates/inferface.F90::emissivity_from_weak_interaction_rates that sets the emissivity to 0 when NaN.

### CODE REVIEW

**Comment by evanoconnor** [comment]
Thanks for this!

Is there a specific reason for removing some of the old rate tables: lmsh and ffn?

**Comment by giraudsimon** [comment]
This corresponds to what we use in our recent work (https://doi.org/10.48550/arXiv.2412.00650). We choose to use shell model calculations only, which generally achieve the highest accuracy for nuclei up to the pf shell and not very far from stability, the new FT-pnRQRPA rates and the approximation for the rest.

**Comment by evanoconnor** [comment]
Ok, But is it possible to leave these in and just have a priority of 0 in the suggested parameters? Since if someone (for whatever reason) wanted to use those old tables they could no longer do it (the lines in the input reader for these old tables are removed as well)

**Comment by giraudsimon** [comment]
Sure, it was stupid of me to remove them from ratelibrary, latest commit cda15bb should fix that.

**Comment by evanoconnor** [comment]
no problem.  What is your suggested priority? is it: Shouldn't the ravlic be highest?

## Rate table priority hierarchy ##
isuzuki		=	1
ilmp			=	2
ioda			=	3
iffn			=	0
ilmsh		=	0
iravlic              =      4
iapprox		=	5

**Comment by giraudsimon** [comment]
For consistency and to include first-forbidden transitions for the pf-shell nuclei, our suggested hierarchy would be iravlic=1 and iapprox=2, the rest 0.

**Comment by evanoconnor** [comment]
@giraudsimon Just coming back to this now as @lbocciol recently asked me about it.  Where exactly is the table ravlicrates.dat?  We can't find it on https://groups.frib.msu.edu/charge_exchange/weakrates.html. I'm guessing it is what is found in [11], but that isn't the format NuLib reads in (and not the format of all the other tables)

**Comment by giraudsimon** [comment]
Thanks for reporting it. The page
https://groups.frib.msu.edu/charge_exchange/weakrates.html has been
updated. Now [11] includes the rates in NuLib format.

Le dim. 11 mai 2025 à 20:14, evanoconnor ***@***.***> a
écrit :

**Pull request merged**
